### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#110]
Hi all,

What is the optimal number for training epochs? Is 25 (by default) normally good or shall I doubled to 50 for better voice quality?
Are anybody tried before increasing the epochs number for more than 25?

Thanks in advance and regards.

**Comment by gillesdegottex** [comment]
Normally, you should wait for the training to stop on its own ("early stop" in Merlin) because it converged.
This is not a good thing to stop it abruptly after a fix given number of iterations.

I usually use 50 and it always stop earlier (in my uses; mainly Arctic and Blizzard voices).

In terms of meta-parameter optimisation, letting it stop whenever it needs also get rid of one parameter to optimise ;)

**Comment by Ali20177** [comment]
Thank you very much ...
