### ISSUE TITLE
World vocoder analysis error

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#162]
For one of our voices (a male voice) the World analysis script is not producing any parameters for a few of the files in the set. The recordings are originally 22kHz but I use 'ch_wave' to downsample to 16kHz. Has anybody had any problems like this? I thought maybe it had to do with the fact that the F0 sometimes goes below 71 Hz but there are still many F0 values above that minimum? I can't see anything wrong with the audio files.

**Comment by ronanki** [comment]
Please provide some example audio files....also try using sox to downsample and extract features.

**Comment by dreamk73** [comment]
I have included two example sentences. The first one, sent1 when converted to 16kHz with ch_wave is not analysed by the extract_features_for_merlin.py script. But when I convert using sox it does produce parameter files. 

However, the second one, sent2 shows the opposite problem. When I convert with ch_wave it produces parameters but when I use sox it doesn't. 

I have played around with the floorF0 value in the constantnumbers.h file but it doesn't seem to help. I can't see anything wrong with the files. Of course I could just exclude the empty files from training, but I would like to understand why WORLD would be unable to produce any features.


[ex.zip](https://github.com/CSTR-Edinburgh/merlin/files/1074410/ex.zip)

**Comment by ronanki** [comment]
This is due to clipping effect, use sox to normalise the audio files. You can check for option --norm [here](http://sox.sourceforge.net/sox.html)

I used original sampling rate as it is and first file seems okay, second file required normalization as shown below:
sox −−norm infile outfile

Configuration variables for 22khz:
if [ "$fs" -eq 22050 ]
then
nFFTHalf=1024
alpha=0.65
fi

You can chose to downsample as well:
sox --norm infile -r 16000 outfile

**Comment by dreamk73** [comment]
Great, thanks so much for helping me figure that out. Should I just run sox --norm per default?
