### ISSUE TITLE
Question in creating state_align labels

### ISSUE THREAD

**Issue by reiinakano** [CSTR-Edinburgh/merlin#178]
When I'm transcribing my audio files, does it make sense to include the "uh"'s and "um"'s? I'm using state alignment.

My question is because I'm using Google's Speech to Text API to get ground truth labels for my .wav files, and they usually get rid of the "uh" and "um" fillers.

**Comment by ronanki** [comment]
The inclusion of fillers actually helps in getting accurate alignments when force-aligned audio files with text -- so, yes, transcribe fillers as well, if you can. 

The steps in [build your own voice](https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/build_your_own_voice/s1) are now finished in order to ease the process of building new voices.

**Comment by reiinakano** [comment]
Thank you so much! All the hacky stuff I did to build my voice feels like wasted effort now but I guess it's much better structured this way. :)
