### ISSUE TITLE
voiced/unvoiced error

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#199]
Dear all,

I am just wonder of meaning that the VUV errors = 0%?
I trained my proposed vocoder parameters under Merlin and I got vuv error = 0%. Is that good? or there is something wrong? Also, I got the F0-RMSE = 22.1.

Appreciated your reply.

**Comment by ronanki** [comment]
`VUV` error can't be zero for sure -- there must be something wrong. Did you use your `F0` with the same name as `lf0`? This can happen, if your input `F0` is always voiced (>0).

Otherwise, there is an [internal function in Merlin](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/acoustic_base.py#L129-L163) which interpolates `F0` and stores its voicing decision as `1/0` with `VUV` parameter before training. At the prediction time, it predicts the `VUV` and compares with reference value and definitely can't be zero.

**Comment by Ali20177** [comment]
Yes, I see. 
Actually, I am using a continuous F0. So, as you said the input F0 is always voiced.

Thanks for your explanation.
