### ISSUE TITLE
Debug train_error = nan, valid_error = nan?

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#208]
I am trying out some different F0 extraction algorithms. When I look at the values computed, I don't see anything wrong with it. The WORLD parameters are computed afterwards with the new F0 values. But when I start training a voice, it bombs on epoch 1 of the train_DNN phase saying that the train_error and valid_error are nan. What is the best way to debug this error? Could it be one file that is giving me trouble and if so, can I easily find which one it is?

**Comment by ronanki** [comment]
If training error or validation error shows nan, that can be because of two reasons:
1. One of the training files has nan value -- you can check your parameter directories and the final `nn_norm_*`using the [test script](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/build_your_own_voice/s1/scripts/test_nan.sh) provided in `egs/build_your_own_voice`.
2. If the learning rate is too high, then also this can happen -- use very low learning rate and then try optimizing it.

**Comment by dreamk73** [comment]
It turned out to be an error in the F0 extraction script.
