### ISSUE TITLE
New filenames for model, log, gen wavdir

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#225]
I noticed in the latest update of Merlin, the filenaming convention changed for the nn model file, the log file and the gen wavdir. Instead of the long DNN_TANH_TANH... it now simply says feed_forward_6_tanh.model. This is ok by me, but when I trained another model in the same directory with only 4 FF tanh layers, the file name didn't change. It overwrites the files in the feed_forward_6_tanh directory instead of creating a new feed_forward_4_tanh directory.

**Comment by ronanki** [comment]
Yes, it was intentional. With so many hyper-parameters to play around, we felt user configurable model name is better than automated model name. For this reason, you need to change the model name as well when you change the architecture or any parameter in the configuration, if you don't want to be overwritten. 

This also helps for test config files -- simply input the model you want to use, rather than adjusting all the hyper-parameters in order to use the automated model name.  Also, we'll soon include the scripts for speaker adaptation, for which user configurable model is best choice rather than automated one, to retrain the model.

**Comment by dreamk73** [comment]
Ok good to know. Thanks!

Esther
