### ISSUE TITLE
versions of world

### ISSUE THREAD

**Issue by seblemaguer** [CSTR-Edinburgh/merlin#227]
Hello,

I have 2 questions : 
  - why are there 2 versions of vocoder world inside merlin ? (knowing that AFAIK only the first one is used)
  - why is the code embedded inside this repo and not the process to compile based on the original world repo ?

I just ask these questions to be sure that before I try to see to a process to retrieve the informations from the main repo I don't miss anything.

**Comment by ronanki** [comment]
world - the one that is currently used, uses variable dimension for BAP
world_v2 - similar to world, with minor changes, and uses fixed-dimension for BAP

However, world_v2 is not a stable version -- works quite well for copy-synthesis, but didn't work for text-to-speech synthesis when tested on SLT corpus. Left it for future development. 

The reason for code embedding inside this repo is -- we made few changes in order to create intermediate features. Hope, it changes in near future -- by taking the latest version and use the patch to do the required task.

**Comment by seblemaguer** [comment]
ok I see :) Thanks

**Comment by m-toman** [comment]
If I may add, the latest WORLD version uses a different F0 extraction mechanism and also encodes voicedness in the BAP, not as F0 == 0. You can find my postings there - I've got Merlin to work with the latest WORLD version, also using the codec provided by WORLD instead of the SPTK mgc<->SP functions. But my results were actually much worse, so I didn't put more work into it (instead I found that for the F0 extraction REAPER performs pretty well in most cases).

**Comment by seblemaguer** [comment]
thanks a lot for this additional information
