### ISSUE TITLE
voice_conversion problem of align_src_with_target

### ISSUE THREAD

**Issue by yj51244** [CSTR-Edinburgh/merlin#262]
for DTW alignment, the length of mgc feats, bap feats and lf0 feats are not the same, but using the same dtw_path_dict. 

File "merlin-master/misc/scripts/voice_conversion/dtw_aligner_festvox.py", line 148, in process
    aligner.align_src_feats(os.path.join(src_lf0_dir, file_id+ ".lf0"), os.path.join(src_aligned_lf0_dir, file_id+ ".lf0"), lf0_dim, dtw_path_dict)
  File "merlin-master/misc/scripts/voice_conversion/align_feats.py", line 22, in align_src_feats
    src_aligned_features[i, ] = src_features[dtw_path_dict[i]]
IndexError: index 1979 is out of bounds for axis 0 with size 1979

**Comment by ronanki** [comment]
WORLD vocoder in general extracts equal number of frames for all parameters. If this is not the case, we need to match externally and then use dtw aligner. 

I'm aware of this problem -- but I never faced this issue with any audio file. Can you please send the audio file where you have faced this issue.

**Comment by yj51244** [comment]
Thank you for your reply. All of my wav files which 44100 hz face this issue,  and I will send you an email with one sample file.

**Comment by ronanki** [comment]
I have checked the file -- and it's good. All parameters are of equal length i.e., 1979. 

Recently, we've updated the feature extraction scripts in order to handle 22.05 KHz and 44.1 KHz. Can you please check your scripts, and compare with current [feature extraction script](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py) in `misc/scripts/vocoder` and [egs script](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/voice_conversion/s1/02_prepare_acoustic_features.sh) in `egs/voice_conversion`.

Once you update the scripts, you can use the below command to test:
```bash
./02_prepare_acoustic_features.sh database/test/wav database/test/feats 44100
```
and to check number of frames in each extracted parameter:
```bash
$MerlinDir/tools/bin/SPTK-3.9/x2x +fa database/test/feats/lf0/2.lf0 | wc -l 
$MerlinDir/tools/bin/SPTK-3.9/x2x +fa database/test/feats/bap/2.bap | xargs -n5 | wc -l 
$MerlinDir/tools/bin/SPTK-3.9/x2x +fa database/test/feats/mgc/2.mgc | xargs -n60 | wc -l 
```

**Comment by yj51244** [comment]
I have found the mistake. I didn't change the "SamplingFreq" from 16000 to 44100 in 01_setup.sh, so for 03_align_src_with_target.sh, the bap_dim was equal to 1 which made the length of bap feats and lf0 feats different.
