### ISSUE TITLE
install compile_unit_selection_tools.sh error

### ISSUE THREAD

**Issue by fancyerii** [CSTR-Edinburgh/merlin#407]
/usr/bin/ld: shared_space/EST_Chunk.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
shared_space/EST_Chunk.o: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
../config/rules/library.mak:106: recipe for target 'libeststring.so' failed
make[1]: *** [libeststring.so] Error 1
config/rules/targets.mak:55: recipe for target 'lib' failed
make: *** [lib] Error 2
Making in bin

**Comment by fancyerii** [comment]
it seems that we should compile compile_unit_selection_tools.sh first, then compile_other_tools.sh.
I compiled compile_other_tools.sh before unit selection tools, then this error occurred.

**Comment by Yablon** [comment]
The reason is that the two scripts, compile_unit_selection_tools.sh and compile_other_tools.sh, both compile  the same package, speech_tools. You compile speech_tools once in compile_other_tools.sh and you compile it again in compile_unit_selection_tools.sh. 
You can set install_speech_tools false in compile_other_tools.sh to solve this problem. So with festival.
