### ISSUE TITLE
Synthesis of longer sentences

### ISSUE THREAD

**Issue by giri946** [CSTR-Edinburgh/merlin#420]
When I'm synthesizing the shorter sentences, the output speech is really good. But for longer sentences, generated durations are not good. Speed of the output speech is increasing linearly. The initial part of speech is very slow and at the end it is too fast.

I'm attaching the synthesized files for reference. Please help in this issue.

[files.zip](https://github.com/CSTR-Edinburgh/merlin/files/2726727/files.zip)

**Comment by dreamk73** [comment]
What does your training set look like? Do you have a good variety of longer sentences in there? If all or most of your sentences are short, it won't learn well as it hasn't seen certain contexts relating to the positional features in the sentence.

**Comment by m-toman** [comment]
I tried a couple tricks like thresholding the durations, but what worked best in the end was randomly concatenating sentences in the training set to artificially produce longer ones (and concat the transcriptions with ",")

**Comment by giri946** [comment]
@dreamk73 

Training set consists of all shorter sentences. There are no longer sentences. 
But, Is it the main reason for getting wrong durations.? Can you please explain briefly..

**Comment by dreamk73** [comment]
There are several questions in the question file that count number of words or syllables between stressed syllables and accented words as well as questions that count the total number of syllables, words, etc in the sentence. If your training data only contains shorter sentences and you are trying to generate a longer sentence, you are inputting features with feature values that do not occur in your training set, so the DNN just makes a wild guess. I would expect it to be worse in the beginning and end due to these counters I just mentioned. There are a few things you could try. One is to limit the counters to a maximum of 5 (but not for the absolute counters, only the relative ones). 

And no, you can't just concatenate shorter sentences together. When people speak, they do different things in longer sentences that are not captured when you concatenate shorter sentences together. The speech rhythm and intonation will be different. Basically, you should have a training set that better represents what you want to synthesize.

**Comment by m-toman** [comment]
Sure concatenation isn't optimal. But I found it works much better than all those thresholding tricks when you can't get more data.
Although I think in the end speaker adaptation by finetuning a pretrained base model solved it better.

**Comment by giri946** [comment]
Thank you @m-toman and @dreamk73 for the explanation.
