### ISSUE TITLE
Meaning of HTS Questions

### ISSUE THREAD

**Issue by kevinmchu** [CSTR-Edinburgh/merlin#463]
I wish to modify the misc/questions/questions-radio_dnn416.hed file, but I am unsure what some of the questions mean. For instance, I understand that C-Vowel is asking whether the current phone is a vowel, but I am unsure what questions such as Seg_Fw mean. Is there a resource somewhere that explains what these questions mean?

**Comment by dreamk73** [comment]
Seg_Fw lists the location of the current segment in the syllable from the beginning of that syllable. Seg_Bw does the same but from the back. I'm not sure where to find more information, but maybe since it is the same as used in the HTS system, there is more information there?

**Comment by RasmusD** [comment]
If you download the hts demo here: http://hts.sp.nitech.ac.jp/?Download
Under the data folder there is a pdf explaining all of the linguistic feature meanings in the label strings.
I believe the feature set extracted by merlin using festival is the same as those used by hts as they also used festival. Though there may be a variety of differences due to different dictionaries etc. etc.
But the symbols are more or less the same I think.

**Comment by kevinmchu** [comment]
That is exactly what I was looking for. Thank you.
