### ISSUE TITLE
Multiprocessing ?

### ISSUE THREAD

**Issue by m7md7sien** [CSTR-Edinburgh/merlin#51]
I noticed that when my friend run merlin on his machine, it utilizes all his CPUs unlike me, when I run merlin on the same data it uses only one CPU and obviously finish much slower than my friend.
how can I activate multi threading in merlin ?
thanks in advance

**Comment by madhavivr** [comment]
did you ever figure out how to activate multi threading?

**Comment by pglushkov** [comment]
Make sure you have proper versions of 'numpy' and BLAS libraries installed. For example in my case, I've installed 'libopenblas' on my machine and Theano could use multi-processing after that.

**Comment by madhavivr** [comment]
Thank you, I'll look to see what was installed on my machine.

**Comment by pglushkov** [comment]
on my Ubuntu 14.04 machine all multi-cpu issues were resolved with simple 'sudo apt-get install libopenblas-dev'

**Comment by madhavivr** [comment]
Thanks again - I talked to my computer administrator and he said I needed to set the "openmp parameter to a number greater than 1".  Not sure where I should set that! The thing that is most bugging me about this is I see the code to run DNN on either GPU or CPU is in submit.sh and if you see the part that runs on CPU there doesn't seem to be a parallelization code there!
if 

....
else
    echo "No GPU is available! Running on CPU..."

    THEANO_FLAGS=$MERLIN_THEANO_FLAGS
    export THEANO_FLAGS
    
    python $@
fi

The MERLIN_THEANO_FLAGS is set in src/setup_env.sh as  MERLIN_THEANO_FLAGS="cuda.root=/opt/6.5.19,floatX=float32,on_unused_input=ignore"


so where is the parallelization code?

**Comment by pglushkov** [comment]
As far as I know, if OpenMP is available, then by default Theano will take up as many cores as is available, so no explicit parallelization code is needed. All the parallelization happens at waaaay more lower level, when optimized BLAS routines (C or FORTRAN) are called. At least in my case Theano could easily occupy all 8 cores without any addfitional actions from me. You can also use the OMP_NUM_THREADS environment variable. If it is >= 1, then its value is an explicit number of cores that you want Theano to occupy. You can set it as:

THEANO_FLAGS="OMP_NUM_THREADS=4,"$MERLIN_THEANO_FLAGS
export THEANO_FLAGS

Instead of 4 you can try to put any number of threads that you like. As I said, in my case after I installed proper verions of BLAS libraries, I did not even have to touch any flags or configs - Theano just used all the available cores for all its linear algebra operations when working on a CPU.

**Comment by tuanad121** [comment]
I realize that we have a python feature_extracting script. I improve it with python multiprocessing. Now it can utilize all available CPUs. Hope it's helpful
[extract_features_for_merlin.py.zip](https://github.com/CSTR-Edinburgh/merlin/files/1160756/extract_features_for_merlin.py.zip)

**Comment by ronanki** [comment]
Thank you -- could you please do the same for [STRAIGHT script](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/straight/extract_features_for_merlin.sh) in python and then make a pull request?

**Comment by tuanad121** [comment]
@ronanki sure, I can do the same with STRAIGHT script.

**Comment by RoelVdP** [comment]
@tuanad121 could you make pull request with code please?

**Comment by tuanad121** [comment]
Hi Roel,
I sent the script to Ronanki long ago. I saw he put it somewhere.
I don't keep the script anymore. Sorry about that :|

Vào CN, 31 thg 3, 2019 vào lúc 14:57 Roel Van de Paar <
notifications@github.com> đã viết:

**Comment by ZackHodari** [comment]
The scripts are [here](https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder)
[world](https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world)
[straight](https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/straight)]
[magphase](https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/magphase)
