### ISSUE TITLE
Directory structure for voice data

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#55]
What is the thinking behind the complicated directory structure in the egs directory? It is confusing to figure out where everything is kept and how to keep track of latest parameter files etc.

**Comment by ronanki** [comment]
egs directory structure is taken from kaldi egs. And then in each voice directory, we have several other sub-directories starting with experiments. This is because, we have different models for acoustic and duration and then we may run multiple experiments with a small change in any parameter while training DNN. Hence, the remaining sub-directories. 

Within the data folder, we have few complicated names for sub-directories, which I do agree -- but, that might be changed in future.
