### ISSUE TITLE
Performance on Short Sentences

### ISSUE THREAD

**Issue by rose4288** [CSTR-Edinburgh/merlin#65]
I recently trained a voice using Merlin, and I found that while I was able to get fairly intelligible results, I found that short synthesized sentences (those that were under 10 words or so) were rushed and unintelligible. Is this an issue others have had?

**Comment by ronanki** [comment]
Probably, you haven't modified the configuration file and trained with few train files -- please check number of train and validation files in configuration file.

**Comment by rose4288** [comment]
I've actually been training on 10,000 training files and a few hundred validation files. I'm wondering if this has something to do with the time stamps in the label files that I'm synthesizing, since I did not have time stamps to begin with and added dummy time stamps, assuming the duration model would correctly estimate them.

**Comment by zhizhengwu** [comment]
Do you have samples? If you are using GV enhancement, it is possible that very short sentences are not as natural as longer ones.

**Comment by sushantakpani** [comment]
I have faced a similar problem. When I synthesized a single sentence with very intelligible results, whereas for a paragraph having four to five sentences results are very poor.
Please find the attachment for used text and synthesized files for reference.

[merli_testdata.zip](https://github.com/CSTR-Edinburgh/merlin/files/885092/merli_testdata.zip)

**Comment by ZackHodari** [comment]
If synthesis sounds rushed this is likely due to bad duration predictions (or incorrect ground-truth durations) provided to the acoustic model.

Synthesising a paragraph using a system trained with sentences is not guaranteed to work due to large length difference between training and synthesis. Typically to synthesise a paragraph, each sentence is synthesised separately and joined together with a small amount of silence manually added (e.g. using [`sox`](http://sox.sourceforge.net))
