### ISSUE TITLE
Multi-Stream Training Information

### ISSUE THREAD

**Issue by JRMeyer** [CSTR-Edinburgh/merlin#94]
Dear Merlin Team & Community, 

I'm looking for some information on multi-stream training.

This question was sparked by trying to find some documentation of the `ms_outs` argument which gets passed to the `train_DNN()` function in the main `run_merlin.py` script.

It seems that `ms_outs` stands for `multi-stream outputs`, and that it may be extracted from the configuration file via `cfg.multistream_outs`.

I also find the `multistream_switch` parameter in various scripts, and it seems this is a related variable.

However, I don't understand what these parameters are. 

I've looked around for information, but I mainly find papers from the vision community on multistream DNNs which incorporate multiple convolutional nets, but I don't see how this would be incorporated in Merlin.

I did find one new paper introducing `multi-stream highway networks`, Wang et al (2016) <http://ssw9.net/papers/ssw9_PS2-7_Wang.pdf>. Another paper I found was Yanagisawa et al (2016) <http://ieeexplore.ieee.org/document/7472661/>. Maybe one of these is what has been implemented in Merlin?

Is there a paper or some literature you can direct me to about multi-stream training in general, and also, could you please shed some light on who it is implemented in Merlin?

Thank you for your time and help, I do appreciate them both!

Best,
Josh

PS - is an issue on GitHub the right place to post this? Maybe there's a forum or google group I'm unaware of.

**Comment by ronanki** [comment]
Those variables were used in the past and left out in the later versions -- as there was no improvement with feed-forward deep neural networks. 

multistream_switch can be helpful, but the weights again need to carefully tuned. At the moment, some parts of the code has few of these variables with some default values but not used internally.

**Comment by JRMeyer** [comment]
Thanks for the quick reply, Srikanth!

I'm just curious now, are those papers I mentioned above what multi-stream training in Merlin is/was?

-josh

**Comment by ronanki** [comment]
Both are in fact different techniques compared to the one in Merlin. 

Wang et al. paper proposed the use of highway networks for SPSS and got much better results when modeled the streams independently instead of joint prediction. This can be achieved even in Merlin by training three different networks for three output features by changing the output__features variable. However, highway networks is not implemented yet. But, you can follow the below implementation for the same using Merlin:
https://github.com/bajibabu/merlin/blob/master/src/models/dnn_keras.py#L191-L247

Yanagisawa et al approach is quite different and is not possible with current setup.

**Comment by JRMeyer** [comment]
Thanks for the elaboration, Srikanth!

I'll close this (non)-issue now.

-josh
